PATH_DATA_RAW = "data/raw/"
PATH_DATA_PROCESSED = "data/processed/"

PATH_DATA_VALIDATION = 'data/validation/'
PATH_DATA_VALIDATION_RESULTS = 'data/results/'
PATH_DATA_TRANSFORMED = 'data/transformed/'
PATH_LOGS_TENSORBOARD = 'logs/tensorboard/'

PATH_DATA_CNRPARK = 'CNRPark-Patches-150x150/'
PATH_DATA_CNREXT = 'CNR-EXT-Patches-150x150/PATCHES/'
PATH_LABELS_CNREXT = 'CNR-EXT-Patches-150x150/LABELS/'
NAME_LABELS_CNREXT = 'all.txt'

PATH_DATA_PKLOT = 'PKLot/PKLotSegmented/'
PATH_LABELS_PKLOT = 'PKLot/LABELS/'
NAME_LABELS_PKLOT = 'all.txt'

PATH_DATA_COMBINED = 'Combined/'

PATH_MODEL = 'models/'
PATH_WEIGHTS = 'weights/'

MODEL_NAME = 'MAlexNet'
WEIGHTS_NAME = 'weights_mAlexNet'

ACCURACY_THRESHOLD = 0.500
IMG_WIDTH = 224
IMG_HEIGHT = 224
N_CHANNELS = 3
N_CLASSES = 2

BATCH_SIZE_TRAIN = 64
BATCH_SIZE_VALIDATION = 64
STEPS_TRAIN = 2831
STEPS_VALIDATION = 707
EPOCHS = 5
LEARNING_RATE = 0.01
WEIGHT_DECAY_RATE = 0.0005
FLAG_NESTEROV = True
MOMENTUM = 0.90
